sudo: false
language: node_js
node_js:
- '10'
install: false
branches:
  only:
  - master
script: make travis
deploy:
- provider: script
  skip_cleanup: true
  script: bash ./tools/publish.sh
  on:
    branch: master
env:
  global:
  - secure: ruSSiZJABTinxtHKfp66/u5QBdHWoraN/Lbvhh8W3O83QaBzgFbKrolKa2g2Uzn8cERqJvd9JaK6q/5qiYxMK+FiD2L9y9hdbO7mMOjU/1lwf/7VnznVcih4tdt7KCd7DHf8LnuoN4YQoXFRfpZU08gRbhc90jrH9PppU6NtQl1txHFgLUPw2G2wrstIjJezMr6u7b+mcVDR0YuJ46n9o6jdwSehIiqAdJEuNXvmVkLS537Ks985/r+jpS1OzhK3DT/O1BHO5HAk2VIUuTH7LkbMsvnXtH8jXbqfwRepAK+p/ph7Cq611ufrJ3in6ZLAqLFvEQyRT+1V+sJWj6QdVQ1szyPkctvKQOxmcG3gfLV3iF6nYq4b2Et85v29Pi1mgYIzmK9beapACOpLoK/VaFwv/90cT2LXWG5WtLe5NOJONDh08oyUQNilYMIYpBzrE8ifigtNyVdErfX8d3UdzkaUBC/kAujKmA0EMqgQT3KerrhAJ7Jp0o2jSPeE1yOSp/yhMYOfGEUZavjd9DTAHIYPrgO6Uk8yF1SSk04aMFVb7CqhnT1VN61MbnR2U6Tk5sebFuNX5bXmHAiDuHksFVKE/0VhGHb+7KinLvXtnqbODF2mrYM/XTjfWGd4/thjcmrnD/Fr4tNlUrJDW71SXAPL6Dz18Jk78FzUGPA4E4o=
  - secure: rYlgh0EV2kBEQNX6iPm3/bRtKL66xbTi49p8nhd2GNURMAXbxSjfGIC0sDq76GV+hRWxpGFeFIdHFRLP2J4mRh37uzbHyPf432cqRLa+h0rQOX+5u371oCN/T1O7e8t5S4y54UXXGzGGpmpIUaUWs9CWFGoC4agORLWuh1G7EbEJGfWUELUS8EQS/zi3pqugINmoEeCD6lRpF5KfhqRoTr5EcdOGmdMguBJ/3YZDPk8YVdC1/n96U+h5H8/YIr5hDVN5Ll85AUyi4rperCW59DZaPFghtv1XypYk2gttWfpfD7wUtBvmAxM3sUKXRd0SbsyabT4aXb2zbsZGMdfFYHpBrfZQJIlJIW/gLYtR9cIxTqrMt4jhu8cVa3z691EBzq+tZp+JhUAe0rTA7qQWRZr7dL0BgkYVhFHH6RDziovG4aGIZovplQGUP/ugqc/HUWxd7JoV6enHHX0ANCzE3jkBUzolU/RJ50Ij34fm+ZW/hpHfctM81FVyICCptHi2LFJunWO72mTI8Nvi5VxX6dAeGcKliYtkdeKCc5ZEbANR82c85J+c+U1LgX07MJvJfkrm5Gk5o62rxgOTib/04V2hMDkpMDbaGsdiYxH8Ow2dtG45agtrAkLt+XeCqtgb4bLj2WFx81H3X6MsxxXtN3VmZT4oSiIDfc2YYXK28OM=
