sudo: false
language: node_js
node_js:
- '10'
install: false
branches:
  only:
  - master
script: make travis
deploy:
- provider: script
  script: curl -X POST -d {} https://api.netlify.com/build_hooks/5d547f070504cc4a52c2a9b2
  on:
    branch: master
- provider: script
  skip_cleanup: true
  script: bash ./tools/publish.sh
  on:
    branch: master
env:
  global:
  - secure: RzFFDDpT9wtdSTa8JzTKqI+1nvOyrLiSduKO/sdMz2ozGM3KVwSv4+m1nYJAeJD4ypgQqMKHPX6MlyWaO8UQ5pvZH7/az+wgv/jJJCS2OpilRJUy0lT7URgGHWn8xCU6+dw3Ou3bOzU+nndub4Lfd23pfSOz7DOL+VpSxavmpaFv2cZB2XBl/zW6W7diVnn/52lj3pUolwX/ATClyIfgu4KD0zIw5BfP4WvMayfGS0hP1J/oTPKMVAFJQZk9WsE+0ZmFn85RrQ+L+A9d41O5z+xinmWWk6R7DpN34F8csD2wQ/GDK0vkzlxJWkT6NHiToVGhdH8sYtT20EC92T8jrCUmib+e+p0PcbXB0gkqTRFl7SxRKCa7v4pOcQqavSLkQ/Xy7htjPQoAnCxK2UOoryXipYwoih0NGG1A+VTloP4hBek2tmSJRByTpV5CMvtnuZgfI/LWDaPqm/S5NsDU9sKbmzsnlFyOMnKZAf3MTBABer53BtXNr8SDEZA6w4BKJuQZWYC4DQX6ROye1KRbY0WEjmhRD6eFd1NOqTtu2v744KBjtpp8OqOvVjY+D56F80G4n0vWIyan9YBNeqjdtP2khvw2oVXOSqPkIY23nZoFKhh0sMauL1vpGrj7bKvJrTnGCqMPFGcioqzgCwrj5P4g/o2n4xvIxQXTj+TfoRw=
  - secure: SUvikB1CSgt7StmZ+D7Ke7cbb/UMj8dV6ap9Nn1ZZOGqsbwyOvza5jh4z2QfQEV56mGSNURJBS0IcbOpCB5fxktIm0lzS/Y6JPLB3lGW4pYSqL3KbQkhG3k6Uhf/KeefkAji33FPHvGpiIlJj/4i4kl1IIQS4nLMBHWLEBT82ONoc01t9uFqSy7tD6dE1xbxwNgNu/iNdlhWfftE2Ft47abIMoI2vT1mx0wZ7H2OzAHGkcUc6QN26f3+hybUZcQlDahk+qn+xahw1Wkw1elKwXFQEZ3aByp6gBB6Zn+5R4AvdI4xP9aK30m7IfX9AD/O5Qni9BS7r1u1oNwufFFcWFsS1VZmKf4+2LFEuMwCoKJ+38u6rUaL0hDMYTfcbT4RC67ewcLMlURdAOlmFdBz3D2ZuJYvO7KaSZL5N0IBVNYRvmoaBrG+dA3Oos1fhqh9mN1MRzN1tzfse+M1zC+fdPRIDNCQVeLVcJNRSps7ZHgKw/LWP+qgrQ4LiCr/Zu5dyLtObvSHiCDAfaxUq5lrSsIZwW9PEbIsOvD7U39mm91SMDmhjOtpn5yRJN/61V0CbZSqYfqXktXmRCcOxWvNn2c2lHWbbVcTnMLuqVs4iyVQeXnz8JmY2c8DECBox9weA+5r2+rDHZ4UMhBn9Mnem/qM7N9YcwSlMUIixwRAxFI=
