[build]
  # This will be run the site build
  command = "npm run netlify"
  # This is the directory is publishing to netlify's CDN
  publish = "src/dist"
  # functions build directory
  functions = "api/dist"
